version: '3.4'

services:
  app:
    build:
      context: .
      target: development
    image: bbb-stress-test:development
    working_dir: /app/
    user: ${DOCKER_USER:-1000}
    cap_add:
      - SYS_ADMIN
    env_file:
      - .env
    volumes:
      - .:/app
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'